spring.application.name=networking
# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Database Configuration (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/networking
spring.datasource.username=root
spring.datasource.password=apoorvar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
#spring.jpa.hibernate.ddl-auto=update   # options: none, validate, update, create, create-drop
spring.jpa.show-sql=true               
  # show SQL queries in console
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Session Configuration
# ===============================
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict


#--------------------------------
#impl errors
#------------------------------
service.user.alreadyExists=User already exists
service.user.registered=User Registered Successfully
service.user.notfound=user not found
service.user.loginInvalidPassword=Invalid password

#--------------------------------
#security secret key
#--------------------------------
jwt.secret=u1h/JS+Bu1CMhGTbQWPhRBPg43yjoH1sugSvWnn0/ds=

#--------------------------------
#file uploads
#--------------------------------

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Material errors
service.material.notFound=Material not found
service.material.noFile=File or URL is required
logging.level.org.springframework.security=DEBUG
server.error.include-message=always
server.error.include-stacktrace=never